{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ab024914-b6e2-404a-9bfc-a7ff81e72994",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PyAEDT INFO: Initializing new Desktop session.\n",
      "PyAEDT INFO: StdOut is enabled\n",
      "PyAEDT INFO: Log on file is enabled\n",
      "PyAEDT INFO: Log on Desktop Message Manager is enabled\n",
      "PyAEDT INFO: Debug logger is disabled. PyAEDT methods will not be logged.\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 4, in <module>\n",
      "PyAEDT ERROR:     hfss = Hfss()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\hfss.py\", line 216, in __init__\n",
      "PyAEDT ERROR:     FieldAnalysis3D.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Analysis3D.py\", line 106, in __init__\n",
      "PyAEDT ERROR:     Analysis.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Analysis.py\", line 143, in __init__\n",
      "PyAEDT ERROR:     Design.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 262, in __init__\n",
      "PyAEDT ERROR:     self._desktop_class = _init_desktop_from_design(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\desktop.py\", line 409, in _init_desktop_from_design\n",
      "PyAEDT ERROR:     return Desktop(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\desktop.py\", line 593, in __init__\n",
      "PyAEDT ERROR:     student_version_flag, version_key, version = self._assert_version(version, student_version)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\desktop.py\", line 884, in _assert_version\n",
      "PyAEDT ERROR:     raise ValueError(\n",
      "PyAEDT ERROR: Specified version 2023.2 is not installed on your system on __init__\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 4, in <module>\n",
      "PyAEDT ERROR:     hfss = Hfss()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\hfss.py\", line 216, in __init__\n",
      "PyAEDT ERROR:     FieldAnalysis3D.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Analysis3D.py\", line 106, in __init__\n",
      "PyAEDT ERROR:     Analysis.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Analysis.py\", line 143, in __init__\n",
      "PyAEDT ERROR:     Design.__init__(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 262, in __init__\n",
      "PyAEDT ERROR:     self._desktop_class = _init_desktop_from_design(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\desktop.py\", line 409, in _init_desktop_from_design\n",
      "PyAEDT ERROR:     return Desktop(*args, **kwargs)\n",
      "PyAEDT ERROR: __init__() should return none, not 'bool' on __init__\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 8, in <module>\n",
      "PyAEDT ERROR:     hfss.load_project(project_path)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 2621, in load_project\n",
      "PyAEDT ERROR:     proj = self.odesktop.OpenProject(file_name)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 505, in odesktop\n",
      "PyAEDT ERROR:     return self._desktop\n",
      "PyAEDT ERROR: 'hfss' object has no attribute '_desktop' on load_project\n",
      "PyAEDT ERROR: Method arguments: \n",
      "PyAEDT ERROR:     file_name = C:\\path_to_your_project\\your_project.aedt \n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 11, in <module>\n",
      "PyAEDT ERROR:     hfss.set_active_design(\"Your_Design_Name\")  # Replace with your design name\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 3858, in set_active_design\n",
      "PyAEDT ERROR:     self._init_design(project_name=self.project_name, design_name=name)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 725, in project_name\n",
      "PyAEDT ERROR:     if self.oproject:\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 1147, in oproject\n",
      "PyAEDT ERROR:     return self._oproject\n",
      "PyAEDT ERROR: 'hfss' object has no attribute '_oproject' on set_active_design\n",
      "PyAEDT ERROR: Method arguments: \n",
      "PyAEDT ERROR:     name = Your_Design_Name \n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 14, in <module>\n",
      "PyAEDT ERROR:     hfss[\"Wire_Diameter\"] = \"20um\"\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 193, in __setitem__\n",
      "PyAEDT ERROR:     self.variable_manager[variable_name] = variable_value\n",
      "PyAEDT ERROR: 'nonetype' object does not support item assignment on __setitem__\n",
      "PyAEDT ERROR: Method arguments: \n",
      "PyAEDT ERROR:     variable_name = Wire_Diameter \n",
      "PyAEDT ERROR:     variable_value = 20um \n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 15, in <module>\n",
      "PyAEDT ERROR:     hfss[\"Coil_Pad_Size\"] = \"500um\"\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 193, in __setitem__\n",
      "PyAEDT ERROR:     self.variable_manager[variable_name] = variable_value\n",
      "PyAEDT ERROR: 'nonetype' object does not support item assignment on __setitem__\n",
      "PyAEDT ERROR: Method arguments: \n",
      "PyAEDT ERROR:     variable_name = Coil_Pad_Size \n",
      "PyAEDT ERROR:     variable_value = 500um \n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR: **************************************************************\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "PyAEDT ERROR:     return _run_code(code, main_globals, None,\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\runpy.py\", line 86, in _run_code\n",
      "PyAEDT ERROR:     exec(code, run_globals)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "PyAEDT ERROR:     app.launch_new_instance()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "PyAEDT ERROR:     app.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "PyAEDT ERROR:     self.io_loop.start()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "PyAEDT ERROR:     self.asyncio_loop.run_forever()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "PyAEDT ERROR:     self._run_once()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "PyAEDT ERROR:     handle._run()\n",
      "PyAEDT ERROR:   File \"C:\\Program Files\\AnsysEM\\Ansys Student\\v232\\Win64\\commonfiles\\CPython\\3_10\\winx64\\Release\\python\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "PyAEDT ERROR:     self._context.run(self._callback, *self._args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "PyAEDT ERROR:     await self.process_one()\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "PyAEDT ERROR:     await dispatch(*args)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "PyAEDT ERROR:     await result\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "PyAEDT ERROR:     await super().execute_request(stream, ident, parent)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "PyAEDT ERROR:     reply_content = await reply_content\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "PyAEDT ERROR:     res = shell.run_cell(\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "PyAEDT ERROR:     return super().run_cell(*args, **kwargs)\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Local\\Temp\\ipykernel_14540\\1275159875.py\", line 16, in <module>\n",
      "PyAEDT ERROR:     hfss[\"Enclosed_Area\"] = \"100um\"\n",
      "PyAEDT ERROR:   File \"C:\\Users\\go29lap\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py\", line 193, in __setitem__\n",
      "PyAEDT ERROR:     self.variable_manager[variable_name] = variable_value\n",
      "PyAEDT ERROR: 'nonetype' object does not support item assignment on __setitem__\n",
      "PyAEDT ERROR: Method arguments: \n",
      "PyAEDT ERROR:     variable_name = Enclosed_Area \n",
      "PyAEDT ERROR:     variable_value = 100um \n",
      "PyAEDT ERROR: **************************************************************\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'Hfss' object has no attribute '_logger'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 19\u001b[0m\n\u001b[0;32m     16\u001b[0m hfss[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEnclosed_Area\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m100um\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;66;03m# Modify the width of all polylines to 20 um\u001b[39;00m\n\u001b[1;32m---> 19\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m obj \u001b[38;5;129;01min\u001b[39;00m \u001b[43mhfss\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmodeler\u001b[49m\u001b[38;5;241m.\u001b[39mobjects:\n\u001b[0;32m     20\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m hfss\u001b[38;5;241m.\u001b[39mmodeler\u001b[38;5;241m.\u001b[39mobjects[obj]\u001b[38;5;241m.\u001b[39mobject_type \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPolyline\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m     21\u001b[0m         hfss\u001b[38;5;241m.\u001b[39mmodeler\u001b[38;5;241m.\u001b[39mchange_property(\n\u001b[0;32m     22\u001b[0m             [\n\u001b[0;32m     23\u001b[0m                 \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNAME:AllTabs\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     37\u001b[0m             ]\n\u001b[0;32m     38\u001b[0m         )\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Analysis3D.py:152\u001b[0m, in \u001b[0;36mFieldAnalysis3D.modeler\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    144\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Modeler.\u001b[39;00m\n\u001b[0;32m    145\u001b[0m \n\u001b[0;32m    146\u001b[0m \u001b[38;5;124;03mReturns\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    149\u001b[0m \u001b[38;5;124;03m    Modeler object.\u001b[39;00m\n\u001b[0;32m    150\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    151\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_modeler \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 152\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlogger\u001b[49m\u001b[38;5;241m.\u001b[39mreset_timer()\n\u001b[0;32m    154\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpyaedt\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodeler\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodeler2d\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Modeler2D\n\u001b[0;32m    155\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpyaedt\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodeler\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodeler3d\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Modeler3D\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\.pyaedt_env\\3_10\\lib\\site-packages\\pyaedt\\application\\Design.py:536\u001b[0m, in \u001b[0;36mDesign.logger\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    528\u001b[0m \u001b[38;5;129m@property\u001b[39m\n\u001b[0;32m    529\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mlogger\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[0;32m    530\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Logger for the design.\u001b[39;00m\n\u001b[0;32m    531\u001b[0m \n\u001b[0;32m    532\u001b[0m \u001b[38;5;124;03m    Returns\u001b[39;00m\n\u001b[0;32m    533\u001b[0m \u001b[38;5;124;03m    -------\u001b[39;00m\n\u001b[0;32m    534\u001b[0m \u001b[38;5;124;03m    :class:`pyaedt.aedt_logger.AedtLogger`\u001b[39;00m\n\u001b[0;32m    535\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 536\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_logger\u001b[49m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'Hfss' object has no attribute '_logger'"
     ]
    }
   ],
   "source": [
    "from pyaedt import Hfss\n",
    "\n",
    "# Launch HFSS and create a new project\n",
    "hfss = Hfss()\n",
    "\n",
    "# Load an existing project\n",
    "project_path = r\"C:\\path_to_your_project\\your_project.aedt\"  # Replace with your project path\n",
    "hfss.load_project(project_path)\n",
    "\n",
    "# Set the active design\n",
    "hfss.set_active_design(\"Your_Design_Name\")  # Replace with your design name\n",
    "\n",
    "# Define or modify parameters\n",
    "hfss[\"Wire_Diameter\"] = \"20um\"\n",
    "hfss[\"Coil_Pad_Size\"] = \"500um\"\n",
    "hfss[\"Enclosed_Area\"] = \"100um\"\n",
    "\n",
    "# Modify the width of all polylines to 20 um\n",
    "for obj in hfss.modeler.objects:\n",
    "    if hfss.modeler.objects[obj].object_type == \"Polyline\":\n",
    "        hfss.modeler.change_property(\n",
    "            [\n",
    "                \"NAME:AllTabs\",\n",
    "                [\n",
    "                    \"NAME:Geometry3DAttributeTab\",\n",
    "                    [\n",
    "                        \"NAME:PropServers\", obj\n",
    "                    ],\n",
    "                    [\n",
    "                        \"NAME:ChangedProps\",\n",
    "                        [\n",
    "                            \"NAME:Width\",\n",
    "                            \"Value:=\", \"20um\"\n",
    "                        ]\n",
    "                    ]\n",
    "                ]\n",
    "            ]\n",
    "        )\n",
    "\n",
    "# Set up a simulation\n",
    "setup = hfss.create_setup(setupname=\"Setup1\")\n",
    "setup.props[\"Frequency\"] = \"1GHz\"\n",
    "setup.props[\"MaximumPasses\"] = 10\n",
    "setup.props[\"MinimumPasses\"] = 2\n",
    "setup.props[\"MaxDeltaS\"] = 0.02\n",
    "setup.update()\n",
    "\n",
    "# Run the simulation\n",
    "hfss.analyze_setup(\"Setup1\")\n",
    "\n",
    "# Export results\n",
    "report = hfss.post.create_report(\"Inductance\", \"Setup1\", \"Rectangular Plot\")\n",
    "report.export_to_file(\"inductance.csv\")\n",
    "\n",
    "# Save the project\n",
    "hfss.save_project()\n",
    "\n",
    "# Release the HFSS instance\n",
    "hfss.release_desktop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99f03c59-f6c6-4f8b-a319-7dbec015f80e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
